version: '3.4'

services:
  catalogdb:
    image: mongo:bionic

  basketdb:
    image: redis:alpine3.13

  discountdb: 
    image: postgres:9.6.22-alpine

  portainer:
    image: portainer/portainer-ce:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgresql_data:
