version: '3.4'

services:
  catalogdb:
    image: mongo:bionic

  basketdb:
    image: redis:alpine3.13

  discountdb: 
    image: postgres:9.6.22-alpine

  orderdb: 
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:management-alpine

  pgadmin: 
    image: dpage/pgadmin4:snapshot
  portainer:                           
    image: portainer/portainer-ce:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount/Discount.GRPC/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Order/Ordering.API/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile


  aspnetrunbasics:
    image: ${DOCKER_REGISTRY-}aspnetrunbasics
    build:
      context: .
      dockerfile: WebApps/AspnetRunBasics/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateways/OcelotApiGateway/Dockerfile

  elasticsearch:
    image: elasticsearch:7.13.3

  kibana:
    image: kibana:7.13.3


  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: WebStatus/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgresql_data:
  pgadmin_data:
  elasticsearch_data:







